# Velodyne_HDL-32E
# TODO

sensor_processor/type: laser
sensor_processor/min_radius: 0.018
sensor_processor/beam_angle: 0.0006
sensor_processor/beam_constant: 0.0015
sensor_processor/ignore_points_above: 2       #Points with a height over this threshold will not be considered valid during the data collection step
sensor_processor/ignore_points_below: -2      #Points with a height over this threshold will not be considered valid during the data collection step
sensor_processor/ignore_points_inside_x_y: 2   #Points with a x or y value below this threshold will not be considered valid during the data collection step.